version: '3'
services:
  board-frontend:
    container_name: board-assistant-frontend
    env_file: ./.env
    # network_mode: host
    image: board-assistant/frontend
    # volumes:
    #   - ./:/usr/board-assistant/frontend
    ports:
      - 3000:3000
